spring.application.name=deliverai-backend

server.port=8084

# ==========================
# DATABASE
# ==========================

spring.datasource.url=jdbc:postgresql://postgres:5432/deliverai

spring.datasource.username=postgres

spring.datasource.password=kiit

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA
# ==========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true